'use strict';

/**
 * Projetos de pesquisa, extensão e desenvolvimento — transcritos integralmente
 * do Currículo Lattes, com descrição, equipe, financiadores e produção associada.
 */

const PROJETOS = [
  /* ------------------------------------------------------------ pesquisa */
  {
    kind: 'pesquisa',
    period: '2017 — Atual',
    status: 'Em andamento',
    role: 'Coordenadora',
    title: 'Elaboração de fitoterápico para tratamento das ações locais induzidas em acidentes por Bothrops atrox',
    description:
      'Uma vez que Bellucia dichotoma demonstrou potencial em bloquear os efeitos locais produzidos pelo veneno botrópico e não neutralizados eficazmente pelo antibotrópico, este projeto tem por objetivo elaborar uma forma farmacêutica, com propriedades anti-inflamatórias e antimicrobiana, a partir de Bellucia dichotoma. Avaliações das propriedades farmacológicas desta formulação serão investigadas vislumbrando a produção, futuramente, de um bioproduto fitoterápico que possa ser utilizado no tratamento complementar à soroterapia nos acidentes por Bothrops atrox.',
    students: 'Doutorado: 1',
    team: 'Maria Cristina dos Santos Sobreira de Sampaio (coordenadora) · Cecília Verônica Nunez · Valéria Mourão de Moura · Rosa Helena Veras Mourão · Luana Travassos Batista · Maria Carolina Scheffer de Souza · Keyla Emanuelle Ramos da Silva',
    funder: 'Fundação de Amparo à Pesquisa do Estado do Amazonas (FAPEAM) — auxílio financeiro',
    output: 2,
  },
  {
    kind: 'pesquisa',
    period: '2012 — Atual',
    status: 'Em andamento',
    role: 'Coordenadora',
    title: 'Purificação de Imunoglobulinas de peixes e arraias Amazônicas',
    description:
      'O presente trabalho visa comparar três métodos bastante utilizados na obtenção de imunoglobulinas a partir de plasma ou de soro: o método do ácido caprílico, a cromatografia de afinidade com proteína estafilocócica A e a cromatografia de afinidade com proteína estreptocócica G, quanto às suas eficácias na purificação de imunoglobulinas de espécies de peixes Amazônicos, além de caracterizar bioquimicamente as imunoglobulinas obtidas destas espécies. As espécies escolhidas para a utilização do soro consistem na arraia Plesiotrygon iwamae, no tambaqui (Colossoma macropomum) e no pirarucu (Arapaima gigas). A seleção de tais espécies se deu em função da ausência de estudos sobre os aspectos imunológicos dessas espécies Amazônicas, conforme evidenciado por revisão da literatura científica nas bases Scopus, Scirus, Pubmed, Lilacs e Portal Periódicos Capes, buscando dados de janeiro de 1987 a novembro de 2012; e do espectro de avaliação ao se comparar dados de um peixe cartilaginoso (a arraia, da classe Chondrichthyes) com peixes ósseos (o tambaqui e o pirarucu, ambos da superclasse Gnathostomata).',
    students: 'Graduação: 2 · Mestrado: 2 · Doutorado: 2',
    team: 'Maria Cristina dos Santos Sobreira de Sampaio (coordenadora) · Consuelo Latorre Fortes-Dias · Camilo Alberto Corrêa de Vasconcellos Dias · Luís André Morais Mariúba · José Dantas Goes Filho · Damy Caroline de Melo Souza · Rafael Luckwu de Sousa',
    output: 8,
  },
  {
    kind: 'pesquisa',
    period: '2011 — 2014',
    status: 'Concluído',
    role: 'Integrante',
    title: 'Anticorpo antifosfolípides e associação com fenômenos trombóticos, em pacientes com hanseníase e manifestações articulares',
    description:
      'O projeto visa avaliar a persistência da positividade do anticorpo anticardiolipina (aCL) e anti β2-glicoproteína (anti-β2GP) em pacientes de alta por cura da hanseníase, que foram positivos em estudo anterior, e avaliar possível associação entre os autoanticorpos estudados e fenômenos trombóticos. Será realizado estudo de corte longitudinal onde serão recrutados os pacientes do estudo anterior: positivos para aFL (25 aCL e 73 anti β2GP) dos 158 pacientes com hanseníase. Os pacientes serão contactados via telefônica e correio para comparecerem à Fundação “Alfredo da Matta”, onde serão entrevistados e avaliados. Será realizada revisão do prontuário pesquisando a existência de fenômenos trombóticos passados e atuais. Para a pesquisa dos anticorpos aFL serão utilizadas as técnicas de ELISA para aCL e anti-β2GP. Espera-se que os resultados esclareçam a correlação da positividade dos anticorpos aFL em doenças infecciosas sem a presença de manifestações clínicas, como ocorre na síndrome antifosfolípides.',
    students: 'Doutorado: 1',
    team: 'Sandra Lúcia Euzébio Ribeiro (coordenadora) · Maria Cristina dos Santos Sobreira de Sampaio · Luiz Fernando de Souza Passos',
    output: 3,
  },
  {
    kind: 'pesquisa',
    period: '2011 — Atual',
    status: 'Em andamento',
    role: 'Coordenadora',
    title: 'Perfil proteico e caracterização das atividades biológicas dos venenos das arraias da Bacia Amazônica (Chondrichthyes/Potamotrygonidae)',
    description:
      'As arraias da família Potamotrygonidae são peixes elasmobrânquios de água doce, distribuídos pelos rios da América do Sul, nas bacias que drenam para o Oceano Atlântico e o mar do Caribe. A família está dividida, atualmente, em quatro gêneros: Paratrygon, Potamotrygon, Plesiotrygon e o recentemente descrito Heliotrygon. No Brasil, as arraias de água doce estão distribuídas nas regiões Norte, Centro-Oeste e Sudeste, sendo os acidentes causados por estes animais mais comuns na região Norte. Estas arraias possuem de 1 a 3 ferrões de dentina, localizados na base da cauda, usados na defesa do animal. O ferrão é coberto por uma bainha tegumentar contendo glândulas mucosas e de veneno. Os acidentes geralmente acontecem quando as pessoas pisam no dorso do animal, escondido sob a areia. Por consequência, a arraia introduz o ferrão no pé ou no calcanhar da vítima, causando um ferimento extremamente dolorido que, muitas vezes, infecciona e leva à necrose do tecido. Na região Amazônica a questão é ainda mais grave, pois os acidentes costumam ocorrer com a população que vive às margens dos rios, em lugares distantes e isolados, muitas vezes sem atendimento médico adequado. O tratamento para as lesões é baseado no uso de anti-inflamatórios e antibióticos, pois ainda não existe antídoto específico para o veneno das arraias de água doce. O presente projeto tem por objetivo caracterizar a ação inflamatória local induzida pelos venenos das arraias Plesiotrygon iwamae, Paratrygon aiereba e de espécies do gênero Potamotrygon. Para isso será feita a raspagem do muco contido tanto no dorso quanto nos ferrões dos animais. As proteínas presentes nos extratos de muco serão quantificadas pelo método de Bradford e seus perfis obtidos em gel de poliacrilamida na presença de dodecil sulfato de sódio (SDS-PAGE). Os estudos in vivo serão realizados em camundongos não-isogênicos (Swiss), incluindo a análise do influxo de células polimorfonucleares e mononucleares.',
    students: 'Graduação: 2 · Mestrado: 1 · Doutorado: 1',
    team: 'Maria Cristina dos Santos Sobreira de Sampaio (coordenadora) · Oscar Tadeu Ferreira da Costa · Juliana Luiza Varjão Lameiras · Wallice Luiz Paxiúba Duncan · Camilo Alberto Corrêa de Vasconcellos Dias · Rafael Rodrigues Costa Oliveira',
    funder: 'Conselho Nacional de Desenvolvimento Científico e Tecnológico (CNPq) — auxílio financeiro',
    output: 8,
  },
  {
    kind: 'pesquisa',
    period: '2011 — Atual',
    status: 'Em andamento',
    role: 'Coordenadora',
    title: 'Inflamação induzida pelo veneno de Bothrops atrox',
    description:
      'Bothrops atrox, popularmente conhecida como jararaca, jararaca-do-rabo-branco ou surucucurana, é a serpente encontrada na região Norte do Brasil. Nesta região, apesar de existirem outros gêneros e espécies da família Viperidae — por exemplo Bothrops brazili, Bothriopsis taeniata, Bothriopsis bilineata e Bothrocophias hyoprora (Bérnils et al., 2010) —, a maioria dos acidentes é atribuída à espécie B. atrox, e seu envenenamento induz simultaneamente ações locais e sistêmicas nas vítimas. Dados clínicos e experimentais já demonstraram que a hemorragia, alteração da coagulação sanguínea, mionecrose e, em alguns casos, insuficiência renal aguda são as principais ações sistêmicas desencadeadas após injeção do veneno de B. atrox. As ações locais são apontadas como de maior importância clínica, pois promovem drástica lesão tecidual, incluindo mionecrose, bolhas, hemorragia e uma proeminente resposta inflamatória caracterizada por edema, dor, eritema, equimose e infiltrado de leucócitos. O presente projeto visa avaliar o perfil de citocinas, COX-1 e COX-2 liberado pela ação do veneno de B. atrox.',
    team: 'Maria Cristina dos Santos Sobreira de Sampaio (coordenadora) · Catarina Teixeira · Vanessa Moreira · Maria Regina D’Império Lima',
    output: 1,
  },
  {
    kind: 'pesquisa',
    period: '2009 — 2011',
    status: 'Concluído',
    role: 'Coordenadora',
    title: 'Imunogenicidade das proteínas constituintes dos venenos de Crotalus simus, Crotalus durissus ruruima e Bothrops asper',
    description:
      'Os venenos das serpentes do gênero Bothrops são considerados bons imunógenos, pois induzem a produção de altos títulos de imunoglobulinas. Em contraste, o veneno da cascavel sul-americana, Crotalus durissus terrificus, é conhecido por interferir na resposta imune humoral de equídeos utilizados na produção de antivenenos. Várias pesquisas demonstraram que o componente supressor da peçonha de C. d. terrificus é a crotoxina — proteína formada por um complexo iônico de dois polipeptídios: um ácido, a crotapotina, e outro básico, a fosfolipase A2. Complexo proteico similar à crotoxina já foi isolado e identificado nos venenos individuais de Crotalus durissus ruruima e em indivíduos jovens de Crotalus simus. A presença de componentes supressores da resposta imunológica nos venenos ofídicos impede a produção de antivenenos eficazes para o tratamento de pacientes acidentados por serpentes. O presente trabalho tem por finalidade estudar a imunogenicidade dos venenos das serpentes Crotalus simus e Bothrops asper, responsáveis pela maioria dos acidentes ofídicos ocorridos na Costa Rica, e de Crotalus durissus ruruima, a cascavel responsável por acidentes graves em Roraima, Brasil. Grupos de cavalos serão imunizados segundo o esquema: grupo I — venenos de C. simus e B. asper; grupo II — venenos de C. d. ruruima e B. asper; grupo III — veneno de B. asper e tampão fosfato salina; grupo IV — veneno de C. simus e tampão fosfato salina; grupo V — C. d. ruruima e tampão fosfato salina. Amostras de sangue serão obtidas desses animais imunizados e as imunoglobulinas isoladas por precipitação com ácido caprílico. As proteínas das peçonhas isoladas por cromatografia em HPLC serão utilizadas no método de ELISA e no preparo de coluna de afinidade para verificar os títulos de anticorpos produzidos.',
    students: 'Graduação: 2',
    team: 'Maria Cristina dos Santos Sobreira de Sampaio (coordenadora) · José María Gutiérrez · Guillermo León · Álvaro Segura · María Herrera · Ricardo Estrada · Mauren Villalta',
    funder: 'Universidad de Costa Rica — cooperação',
    output: 2,
  },
  {
    kind: 'pesquisa',
    period: '2009 — Atual',
    status: 'Em andamento',
    role: 'Coordenadora',
    title: 'Perfil Microbiológico, de Citocinas e Celular (Leucócitos Totais e Linfócitos B e T) presentes na saliva e no fluido crevicular de adultos com Periodontite Crônica em Manaus-AM',
    description:
      'As doenças gengivais e periodontais, em suas diversas formas e classificações, atingem o homem desde os primórdios. São doenças infecciosas e inflamatórias que acometem os tecidos de proteção e suporte dos dentes (gengiva, cemento, ligamento periodontal e osso alveolar). Levam à inflamação gengival e posterior reabsorção do osso ao redor das raízes dentárias se não tratadas precocemente. A evolução deste processo pode levar à perda dentária, dependendo do nível de perda óssea atingido. O fator etiológico primário é a infecção por bactérias periodontopatogênicas como Aggregatibacter actinomycetemcomitans, Porphyromonas gingivalis, Tannerella forsythia, Prevotella intermedia, Eikenella corrodens e Treponema denticola. O fator microbiológico pode ser agravado pela má higiene bucal, e fatores sistêmicos como a gravidez também podem alterar as respostas periodontais. O perfil microbiológico da doença periodontal pode variar de acordo com a região, e essas bactérias liberam produtos como enzimas, endo e exotoxinas que, dependendo da suscetibilidade e resposta imune do hospedeiro, provocarão danos maiores ou menores ao periodonto. Até o presente, o diagnóstico das doenças periodontais é clínico, o que permite apenas a avaliação pregressa da doença. Estudos recentes sugerem o desenvolvimento de técnicas que permitam o diagnóstico das fases ativas da periodontite, além da identificação do risco ao desenvolvimento das doenças periodontais.',
    students: 'Mestrado: 1',
    team: 'Maria Cristina dos Santos Sobreira de Sampaio (coordenadora) · Álvaro L. Bertho · Priscilla Farias Naiff · Patrícia Puccinelli Orlandi Nogueira',
    output: 4,
  },
  {
    kind: 'pesquisa',
    period: '2008 — 2013',
    status: 'Concluído',
    role: 'Integrante',
    title: 'Estudo da Genética Molecular da Artrite Reumatóide e da Tuberculose na Amazônia',
    description:
      'Verificar os polimorfismos de alguns genes envolvidos na resposta imune de pacientes portadores de Artrite Reumatóide e Tuberculose.',
    students: 'Doutorado: 1',
    team: 'Antônio Luiz Boechat (coordenador) · Maria Cristina dos Santos Sobreira de Sampaio · M. M. Ogusku · Aya Sadahiro',
    output: 4,
  },
  {
    kind: 'pesquisa',
    period: '2008 — 2010',
    status: 'Concluído',
    role: 'Integrante',
    title: 'Avaliação de métodos de extração de DNA e de identificação de dermatófitos por análise de PCR-RFLP',
    description:
      'Diagnóstico molecular diferencial das espécies de dermatófitos mais frequentes da região Amazônica.',
    students: 'Doutorado: 1',
    team: 'Maria Zeli Moreira Frota (coordenadora) · Maria Cristina dos Santos Sobreira de Sampaio · Aya Sadahiro · João Vicente Braga de Souza',
    funder: 'Fundação de Amparo à Pesquisa do Amazonas — auxílio financeiro / Ministério da Saúde — auxílio financeiro',
    output: 1,
  },
  {
    kind: 'pesquisa',
    period: '2006 — 2011',
    status: 'Em andamento',
    role: 'Coordenadora',
    title: 'Qualidade de Vida em pacientes diabéticos com feridas nos pés',
    description: '',
    students: 'Mestrado: 1',
    team: 'Maria Cristina dos Santos Sobreira de Sampaio (coordenadora) · Selma Perdomo',
    funder: 'Universidade do Estado do Amazonas — cooperação',
    output: 1,
  },
  {
    kind: 'pesquisa',
    period: '2006 — 2010',
    status: 'Concluído',
    role: 'Coordenadora',
    title: 'Avaliação dos Níveis de Stress Psicológico em Médicos Residentes e Não Residentes dos Hospitais Universitários da UFAM: Aspectos Imunológicos e Psicológicos',
    description:
      'O projeto visa avaliar a fase de stress psicológico e correlacioná-la com os títulos de imunoglobulinas das classes A, G e M, concentração de proteínas, atividade da enzima amilase, fluxo salivar e células presentes na saliva de médicos residentes e não residentes dos Hospitais Universitários da UFAM.',
    students: 'Graduação: 3',
    team: 'Maria Cristina dos Santos Sobreira de Sampaio (coordenadora) · Nathália Matos Gomes · Maria Alice D’Ávila Becker · Marilise Katsurayama · Fabiano Makimoto · Francisco Flauber Duarte dos Santos Filho',
    funder: 'Conselho Nacional de Desenvolvimento Científico e Tecnológico (CNPq) — bolsa',
    output: 4,
  },
  {
    kind: 'pesquisa',
    period: '2006 — 2010',
    status: 'Em andamento',
    role: 'Coordenadora',
    title: 'Desenvolvimento de imunossensor para detecção de Fator de Necrose Tumoral (TNF-alfa)',
    description:
      'Nanotecnologia pode ser definida como a ciência que cria materiais funcionais, dispositivos e sistemas controladores de matéria em escala de um a cem nanômetros, e que explora novas propriedades e fenômenos nessa mesma escala. Existe ampla utilização de nanoestruturas em sistemas biotecnológicos (biossensores) para aplicações diagnósticas ou de detecção biológica, justificada pelas propriedades altamente controladas dessas estruturas. Os biossensores foram definidos como sistemas analíticos que incorporam materiais biológicos (tecidos, microrganismos, organelas, receptores celulares, enzimas, anticorpos, ácidos nucleicos, entre outros), derivados biológicos (anticorpos e proteínas recombinantes) ou biológicos sintéticos, em superfícies de transdutores físico-químicos ou microssistemas integrados, ópticos, eletroquímicos, termométricos, piezoelétricos, magnéticos ou micromecânicos. A MAM (Monocamada Automontada) ou SAM (Self-Assembled Monolayer) é formada a partir de técnicas de imobilização sobre suportes ou substratos sólidos, que incluem materiais como ouro, prata, platina, vidro, quartzo, ligas metálicas, óxidos (SiO2, Al2O3, SnO2, TiO2), nitreto (N4Si3), polímeros orgânicos e biomateriais. No presente estudo foi desenvolvido um biossensor baseado na interação antígeno-anticorpo, pela imobilização de um anticorpo monoclonal em superfícies modificadas de ouro, para reconhecimento específico da citocina pró-inflamatória Fator de Necrose Tumoral Alfa (TNF-alfa). Por apresentar ação endócrina, o TNF-alfa pode ser detectado na circulação sanguínea de pacientes com septicemia, artrite reumatóide, doença de Crohn e psoríase, entre outras. A Ressonância de Plasma de Superfície (SPR) foi utilizada como método analítico para caracterização do biossensor.',
    students: 'Mestrado: 1',
    team: 'Maria Cristina dos Santos Sobreira de Sampaio (coordenadora) · Michella Bezerra Lima · Lauro Kubota',
    funder: 'Universidade Estadual de Campinas — cooperação',
    output: 1,
  },
  {
    kind: 'pesquisa',
    period: '2005 — 2010',
    status: 'Em andamento',
    role: 'Coordenadora',
    title: 'Associação entre polimorfismos de receptores eritrocitários e a resistência ou suscetibilidade a infecção malárica no Estado do Amazonas, Brasil',
    description:
      'A malária é a mais importante doença parasitária do mundo, tendo exercido forte efeito na evolução humana. Um crescente corpo de evidências indica que tanto o risco de adquirir infecções como o risco de desenvolver severas complicações têm sido determinados por fatores genéticos do hospedeiro e pelo genótipo do parasito infectante. Isolados selvagens de parasitas de malária podem mostrar maior variabilidade de vias de invasão quando comparados aos cultivados, mostrando que em áreas endêmicas os parasitos podem ter desenvolvido diferentes habilidades para invadir tipos particulares de hemácias. A glicoproteína eritrocitária Duffy é necessária para a invasão de hemácias humanas por merozoítos de Plasmodium vivax, havendo provavelmente importância de seus polimorfismos no processo da infecção malárica.',
    students: 'Doutorado: 1',
    team: 'Maria Cristina dos Santos Sobreira de Sampaio (coordenadora) · Francimary de Oliveira Cavalcante · Sérgio Roberto Lopes Albuquerque',
    funder: 'FAPEAM — auxílio financeiro / Fundação de Hematologia e Hemoterapia do Amazonas — cooperação',
    output: 3,
  },
  {
    kind: 'pesquisa',
    period: '2005 — 2006',
    status: 'Em andamento',
    role: 'Coordenadora',
    title: 'Avaliação da toxicidade do extrato hidro-alcoólico e das frações isoladas de Brosimum acutifolium no tratamento da artrite induzida por adjuvante completo de Freund em ratos Lewis',
    description: '',
    students: 'Graduação: 1',
    team: 'Maria Cristina dos Santos Sobreira de Sampaio (coordenadora)',
    output: 1,
  },
  {
    kind: 'pesquisa',
    period: '2005 — 2006',
    status: 'Em andamento',
    role: 'Coordenadora',
    title: 'Avaliação do tratamento da artrite induzida por adjuvante de Freund em ratos Lewis com as frações isoladas de Brosimum acutifolium',
    description: '',
    team: 'Maria Cristina dos Santos Sobreira de Sampaio (coordenadora)',
  },
  {
    kind: 'pesquisa',
    period: '2005 — Atual',
    status: 'Em andamento',
    role: 'Coordenadora',
    title: 'Psiconeuroimunologia: Estudo comparativo do stress psicológico em estudantes de Medicina — aspectos imunológicos e psicológicos',
    description:
      'Avaliar os títulos de imunoglobulinas e concentração de proteínas nas amostras de saliva coletadas no início do ano letivo e durante as provas finais dos alunos de Medicina com ou sem stress psicológico. O trabalho visa também quantificar e fenotipar as células presentes na saliva e quantificar o fluxo salivar desses estudantes.',
    students: 'Graduação: 4 · Doutorado: 1',
    team: 'Maria Cristina dos Santos Sobreira de Sampaio (coordenadora) · Nathália Matos Gomes · Maria Alice D’Ávila Becker · Fabiano Makimoto · Edijane Paredes-Garcia · Marilise Katsurayama · Linda Luciana Oliveira Santana · Antônio Luiz Boechat · Nathalie Marte Ureña',
    funder: 'Conselho Nacional de Desenvolvimento Científico e Tecnológico (CNPq) — bolsa',
    output: 10,
  },
  {
    kind: 'pesquisa',
    period: '2004 — 2010',
    status: 'Em andamento',
    role: 'Coordenadora',
    title: 'Dermatose experimental em ratos wistar, causada por Drulia uruguayensis Bonetto & Ezcurra de Drago, 1968 (Porifera: Metaniidae)',
    description:
      'Migração celular local, em camundongos não-isogênicos, causada pelo contato com a esponja de água doce Drulia uruguayensis Bonetto & Ezcurra de Drago, 1968 (Porifera: Metaniidae) e suas espículas. As esponjas de água doce, abundantes na região Amazônica, onde têm o nome popular de cauixi, cauxi ou cauí, são conhecidas desde o início do século XX como causadoras de dermatose. Diferentemente das esponjas marinhas, que são estudadas há algumas décadas em relação às suas propriedades bioquímicas e atividades biológicas, esse conhecimento ainda não foi pesquisado entre as esponjas dulciaquícolas, tanto mais na Amazônia. Com o objetivo de determinar quais constituintes provocam reação dermatológica, foi idealizado e realizado um estudo experimental utilizando três formas de preparo de esponjas de água doce (esponjas íntegras, maceradas ou suas espículas isoladas — megascleras). Para o experimento foi utilizada a esponja dulciaquícola Drulia uruguayensis, com ocorrência generalizada nos lagos de várzea da Amazônia.',
    students: 'Graduação: 1 · Mestrado: 1',
    team: 'Maria Cristina dos Santos Sobreira de Sampaio (coordenadora) · Alexandre de Oliveira Magalhães · José Fernando Marques Barcellos · Cecília Volkmer Ribeiro · João Luiz Costa Cardoso',
    output: 4,
  },
  {
    kind: 'pesquisa',
    period: '2004 — 2009',
    status: 'Concluído',
    role: 'Integrante',
    title: 'Gerenciamento dos Resíduos Sólidos do Município de Presidente Figueiredo (AM)',
    description: '',
    students: 'Mestrado: 1',
    team: 'Genilson Pereira Santana (coordenador) · Maria Cristina dos Santos Sobreira de Sampaio · Ana Lúcia Machado',
    funder: 'EletroNorte — auxílio financeiro',
    output: 3,
  },
  {
    kind: 'pesquisa',
    period: '2004 — 2006',
    status: 'Concluído',
    role: 'Coordenadora',
    title: 'Prospecção de extratos e frações de Peltodon radicans na artrite induzida por Adjuvante em ratos Lewis',
    description: '',
    students: 'Graduação: 1',
    team: 'Maria Cristina dos Santos Sobreira de Sampaio (coordenadora) · Luiz Fernando Passos',
    output: 3,
  },
  {
    kind: 'pesquisa',
    period: '2004 — 2005',
    status: 'Em andamento',
    role: 'Coordenadora',
    title: 'Estudo fitoquímico da espécie vegetal Brosimum acutifolium',
    description:
      'A artrite reumatóide (AR) é uma doença crônica e multissistêmica de etiologia desconhecida, cuja característica principal é uma sinovite inflamatória persistente que envolve todas as juntas sinoviais, preferentemente as periféricas, em forma simétrica de distribuição e com potencial deformante variável. Acreditava-se, até certo tempo atrás, que a grande maioria dos pacientes portadores de AR teria uma doença branda. Sabe-se, no entanto, hoje em dia, que até 50% param de trabalhar dentro de dez anos a contar do início da doença. É uma doença bastante comum, acometendo cerca de 1% da população geral. A Brosimum acutifolium é uma espécie vegetal da Amazônia, de baixa densidade populacional nas matas de terra firme, utilizada popularmente para fins terapêuticos, com imputadas propriedades “antirreumáticas”. Conhecida no vulgo como “mururé”, já foi estudada em levantamento etnofarmacológico que demonstrou que seu extrato hidroalcoólico é usado na medicina folclórica da Amazônia para doenças reumáticas crônicas e deformantes. Os efeitos terapêuticos e tóxicos do extrato bruto já foram observados em ensaio piloto randomizado e controlado, em pacientes com artrite reumatóide, com resultados preliminares favoráveis. Paralelamente, a Brosimum acutifolium foi submetida a processo de fracionamento químico, com subprodutos que aguardam demonstração de eficácia/tolerabilidade em modelo animal. O modelo animal clássico para a artrite reumatóide é o rato Lewis, no qual a artrite é induzida pela administração intradérmica, na base da cauda, do adjuvante completo de Freund.',
    students: 'Graduação: 1',
    team: 'Maria Cristina dos Santos Sobreira de Sampaio (coordenadora) · Luiz Fernando Passos · Antônio Flávio C. Alcântara',
    funder: 'Universidade Federal de Minas Gerais — cooperação',
    output: 4,
  },
  {
    kind: 'pesquisa',
    period: '2002 — 2010',
    status: 'Concluído',
    role: 'Coordenadora',
    title: 'Doença Hemolítica do Recém-Nascido e a relação com aloanticorpos eritrocitários em gestantes Rh- atendidas no HEMOAM',
    description:
      'A presença de aloanticorpos eritrocitários da classe G, na circulação materna, pode causar sérias consequências ao neonato. As mulheres Rh negativo podem ser aloimunizadas em diversas situações consideradas de risco, como partos de filhos Rh positivo, aborto, amniocentese e transfusões sanguíneas. Neste estudo foi verificada a presença de aloanticorpos, regulares e irregulares, em gestantes atendidas no Programa de Gestantes Rh Negativo (PGRhN) da Fundação de Hematologia e Hemoterapia do Amazonas (HEMOAM). Para a realização do estudo retrospectivo foram levantados os registros de gestantes atendidas durante o ano de 2003, como também os dados de seus recém-nascidos. No estudo prospectivo, foram analisadas amostras de sangue de gestantes atendidas no PGRhN entre abril e novembro de 2004, como também de seus recém-nascidos. Todos os testes utilizados foram preconizados pelo Manual Técnico da American Association of Blood Bank (2005).',
    students: 'Mestrado: 1',
    team: 'Maria Cristina dos Santos Sobreira de Sampaio (coordenadora) · Francimary de Oliveira Cavalcante · Sérgio Roberto Lopes Albuquerque',
    funder: 'Fundação de Hematologia e Hemoterapia do Amazonas — cooperação',
    output: 2,
  },
  {
    kind: 'pesquisa',
    period: '2002 — 2007',
    status: 'Concluído',
    role: 'Coordenadora',
    title: 'Polimorfismo do gene PDCD1 em pacientes da Amazônia com Lúpus Eritematoso Sistêmico',
    description: '',
    students: 'Graduação: 1 · Doutorado: 1',
    team: 'Maria Cristina dos Santos Sobreira de Sampaio (coordenadora) · Luiz Fernando Passos',
    output: 4,
  },
  {
    kind: 'pesquisa',
    period: '2002 — 2006',
    status: 'Concluído',
    role: 'Coordenadora',
    title: 'Composição da Saliva de Pacientes Irradiados na Região de Cabeça e Pescoço',
    description: '',
    students: 'Mestrado: 1',
    team: 'Maria Cristina dos Santos Sobreira de Sampaio (coordenadora) · Lia Mizobe Ono · Maria Augusta Bessa Rebelo',
    funder: 'Fundação de Amparo à Pesquisa do Amazonas — auxílio financeiro',
    output: 3,
  },
  {
    kind: 'pesquisa',
    period: '2001 — 2004',
    status: 'Concluído',
    role: 'Integrante',
    title: 'Comparação entre a crotamina do veneno de Crotalus durissus ruruima e a do veneno de C. d. terrificus',
    description: '',
    students: 'Mestrado: 1',
    team: 'Antônio Flávio C. Alcântara (coordenador) · Maria Cristina dos Santos Sobreira de Sampaio · Antônio J. N. Fernandes',
    funder: 'Universidade Federal de Minas Gerais — cooperação',
  },
  {
    kind: 'pesquisa',
    period: '1995 — Atual',
    status: 'Em andamento',
    role: 'Coordenadora',
    title: 'Variabilidade dos venenos individuais de Crotalus durissus ruruima, a subespécie da região Amazônica',
    description:
      'Variação intrapopulacional dos componentes proteicos e das atividades biológicas dos venenos de indivíduos adultos de Crotalus durissus ruruima.',
    students: 'Graduação: 3',
    team: 'Maria Cristina dos Santos Sobreira de Sampaio (coordenadora) · Consuelo Latorre Fortes-Dias · Eduardo Borges Assis',
    funder: 'CNPq — bolsa e auxílio financeiro / Fundação Ezequiel Dias — cooperação',
    output: 12,
  },
  {
    kind: 'pesquisa',
    period: '1995 — Atual',
    status: 'Em andamento',
    role: 'Coordenadora',
    title: 'Espécies vegetais Amazônicas utilizadas popularmente para o tratamento de acidentes por serpentes',
    description:
      'Envenenamentos por serpentes do gênero Bothrops sp. resultam em efeitos locais e sistêmicos que tendem a desenvolver-se simultaneamente. Lesões locais incluem edema, dor, eritema, cianose, necrose e celulite. Atividades hemorrágicas, fosfolipásicas e proteolíticas dos venenos botrópicos têm sido relacionadas à patogênese destas lesões e sintomas. Estes eventos relacionados à inflamação, como o aumento da permeabilidade vascular e a dor, têm sido atribuídos à liberação local de moléculas como histamina, bradicinina, citocinas e anafilotoxinas. As coagulopatias provocadas por acidentes botrópicos resultam da depleção de fatores da coagulação, enquanto os sangramentos espontâneos são atribuídos a hemorraginas causadoras de danos ao endotélio vascular, sendo algumas bem caracterizadas como metaloproteinases. Os soros antibotrópicos não são eficazes em neutralizar essas ações locais, principalmente quando o tratamento não é imediato. Sendo assim, a amputação de membros acometidos ainda é uma realidade. No Amazonas, devido às longas distâncias existentes entre os locais onde ocorre o acidente e o atendimento médico, os pacientes demoram a receber o tratamento soroterápico específico. Além disso, os soros antiofídicos produzidos no Brasil não são eficazes em neutralizar a peçonha de Bothrops atrox, que comprovadamente é a mais tóxica para atividade local. Na região amazônica, os pacientes utilizam plantas medicinais pela dificuldade de obter tratamento soroterápico. Trabalhos de nosso grupo constataram a eficácia de Peltodon radicans Pohl no bloqueio da atividade edematogênica do veneno de Bothrops atrox. O presente projeto tem por finalidade estudar a toxicidade dos extratos aquosos de folhas e flores de espécies vegetais utilizadas popularmente no tratamento do acidente ofídico. Visa também avaliar a atividade anti-inflamatória, anticoagulante e antiagregante plaquetária frente a modelos que permitam evidenciar mecanismos farmacológicos e moleculares de diferentes tipos de extratos.',
    students: 'Graduação: 3 · Mestrado: 1 · Doutorado: 3',
    team: 'Maria Cristina dos Santos Sobreira de Sampaio (coordenadora) · C. H. Franciscon · M. O. Mafra · Célio Campos Borges · Antônio Luiz Boechat · Augusto José Cavalcanti Neto · Antônio Flávio C. Alcântara · Dorila Piló-Veloso · Habdel N. R. Costa · Oscar Tadeu Ferreira da Costa · Luciana Tezza · Alcineide Lima Magalhães · Valéria Mourão de Moura · Thaís Pereira da Silva',
    output: 27,
  },
  {
    kind: 'pesquisa',
    period: '1992 — 2018',
    status: 'Concluído',
    role: 'Coordenadora',
    title: 'Ofidismo no Amazonas',
    description: 'Levantamento dos acidentes ofídicos no Amazonas.',
    students: 'Graduação: 16',
    team: 'Maria Cristina dos Santos Sobreira de Sampaio (coordenadora) · R. P. Sá-Neto · Célio Campos Borges · Aya Sadahiro · Marco Antonio Cruz Rocha · Aldrin Verçosa Dias · Joaquim Alfredo Eduardo S. Loureiro · Alexandre G. Borja · Antônio Luiz Boechat · Augusto José Cavalcanti Neto · Fabíola da Silva Maciel · Lilianne W. Bindá · Paulo C. Escóssio · Ana Cláudia e Silva Barros · Daniela Pampolha Fernandes · Cristina da Silva Melo · Megume Sadahiro',
    funder: 'Conselho Nacional de Desenvolvimento Científico e Tecnológico (CNPq) — bolsa',
    output: 21,
  },

  /* ------------------------------------------------------------ extensão */
  {
    kind: 'extensao',
    period: '2021 — Atual',
    status: 'Em andamento',
    role: 'Integrante',
    title: 'Rodas de conversa sobre Biofísica e Imunologia Clínica entre estudantes de países Lusófonos',
    description: '',
    team: 'Fabio Moroni (coordenador) · Maria Cristina dos Santos Sobreira de Sampaio',
  },
  {
    kind: 'extensao',
    period: '2001 — Atual',
    status: 'Em andamento',
    role: 'Coordenadora',
    title: 'MEDensina',
    description:
      'O MEDensina tem como objetivo ministrar palestras com temas relacionados à saúde e à sexualidade para estudantes da rede pública e privada de ensino fundamental e médio, despertando a consciência da população em relação à cidadania e à saúde, de forma a integrar a Universidade à comunidade, além de ampliar a formação dos alunos de graduação, futuros profissionais da área da saúde. O MEDensina é um projeto que alcança grande aceitação na comunidade. Percebemos isso à medida que somos convidados para voltar às instituições; muitas destas querem firmar um elo para que as palestras sejam constantes naquela instituição.',
    students: 'Graduação: 30',
    team: 'Maria Cristina dos Santos Sobreira de Sampaio (coordenadora) · Ana Cyra dos Santos Lucas',
    funder: 'Secretaria de Estado da Educação e Qualidade do Ensino — auxílio financeiro',
    output: 1,
  },
  {
    kind: 'extensao',
    period: '1994 — 2000',
    status: 'Concluído',
    role: 'Coordenadora',
    title: 'Levantamento dos acidentes ofídicos no Interior do Amazonas',
    description:
      'Os prontuários de acidentes ofídicos foram consultados e os dados obtidos para elaboração da incidência em cada município do Estado do Amazonas.',
    team: 'Maria Cristina dos Santos Sobreira de Sampaio (coordenadora) · Célio Campos Borges · Marco Antonio Cruz Rocha · Aldrin Verçosa Dias · Joaquim Alfredo Eduardo S. Loureiro · Cristiano S. Paiva · Fabíola da Silva Maciel · Cristina da Silva Melo · Antônio Luiz Boechat',
  },

  /* ------------------------------------------------------ desenvolvimento */
  {
    kind: 'desenvolvimento',
    period: '2012 — Atual',
    status: 'Em andamento',
    role: 'Integrante',
    title: 'Sistema de Notificação de Acidentes por Arraias (SNAA)',
    description:
      'O envenenamento causado por arraias no Amazonas é frequente; no entanto, existem poucas notificações, o que dificulta o conhecimento da sintomatologia e da epidemiologia desses acidentes. Por isso o presente projeto tem por finalidade: construir e disponibilizar um sistema WEB para possibilitar que a comunidade em geral e os profissionais de saúde notifiquem os acidentes causados por arraias ocorridos no Estado do Amazonas; identificar as informações que devem compor um quadro de notificação de acidentes por arraias; especificar os requisitos (funcionais e não-funcionais) necessários para a implementação do sistema de notificação, avaliando criticamente a viabilidade de cada requisito; e implementar o sistema de notificação de acidentes por arraia, levando em consideração problemas inerentes ao contexto de aplicações WEB, tais como a segurança das comunicações.',
    students: 'Graduação: 1',
    team: 'Andrea P. Mendonça (coordenadora) · Maria Cristina dos Santos Sobreira de Sampaio · Ronei Macedo Gualberto',
  },
];

module.exports = { PROJETOS };
