'use strict';

/**
 * Produção bibliográfica completa, transcrita do Currículo Lattes
 * (ID 4923902785529755, atualizado em 24/02/2025).
 *
 * `citations` traz o número do Web of Science quando informado no Lattes;
 * `scopus` traz o do Scopus. `highlight` marca os trabalhos de maior impacto.
 */

/* ---------------------------------- artigos completos em periódicos (98) */

const ARTIGOS = [
  {
    year: 2024,
    authors: 'ANJOS, MARISSA BRAGA DOS; MOURA, VALÉRIA MOURÃO DE; LAMEIRAS, JULIANA LUIZA VARJÃO; DIAS, LUCAS CASTANHOLA; MOURÃO, ROSA HELENA VERAS; SANTOS, MARIA CRISTINA DOS-; COSTA, OSCAR TADEU FERREIRA DA',
    title: 'Exploring the Protective Effects of Bellucia dichotoma Cong. Aqueous Extract on Spleens Following Bothrops atrox Envenomation in Mice: A Stereological Investigation',
    venue: 'Journal of Advances in Biology & Biotechnology',
    details: 'v. 27, p. 233-246',
    highlight: 1,
  },
  {
    year: 2023,
    authors: 'UREÑA, N. M.; MAIA, M. L. S.; DOS SANTOS, MARIA CRISTINA; BOECHAT, A. L. R.; FURTADO, S. C.',
    title: 'Depression and anxiety are triggers for Rheumatoid Arthritis — A Systematic Review Protocol',
    venue: 'Scientia Amazonia',
    details: 'v. 12, p. B18-B25',
  },
  {
    year: 2022,
    authors: 'MELO-SOUZA, D. C.; CHAGAS, E. C.; LUCKWU-SOUSA, R.; DOS-SANTOS, MARIA CRISTINA',
    title: 'Profile of local and systemic humoral immune response in Colossoma macropomum infected by Neoechinorhynchus buttnerae',
    venue: 'Aquaculture Research (Online)',
    details: 'v. 53, p. 1131-1135',
    citations: 2,
    scopus: 2,
  },
  {
    year: 2021,
    authors: 'SOUZA, M. C. S.; DE MOURA, VALÉRIA MOURÃO; MOURAO, R. H. V.; FACHIN-ESPINAR, M. T.; NUNEZ, C. V.; DOS-SANTOS, MARIA CRISTINA',
    title: 'Antimicrobial activity of Amazonian plant species against the causative agents of secondary infection in snakebites',
    venue: 'Revista Fitos (ALANAC)',
    details: 'v. 15, p. 280-297',
  },
  {
    year: 2021,
    authors: 'BATISTA, L. T.; DOS-SANTOS, MARIA CRISTINA',
    title: 'Acidentes atribuídos à serpente Bothrops atrox: Imunofisiopatologia e tratamento',
    venue: 'Scientia Amazonia',
    details: 'v. 10, p. CB44-CB66',
  },
  {
    year: 2021,
    authors: 'KIELING, A. C.; SANTANA, G. P.; DOS-SANTOS, MARIA CRISTINA; NETO, J.; PINO, G.; SANTOS, M.; DUVOISIN JR, S.; PANZERA, T.',
    title: 'Wood-plastic Composite Based on Recycled Polypropylene and Amazonian Tucumã (Astrocaryum aculeatum) Endocarp Waste',
    venue: 'Fibers and Polymers',
    details: 'v. 22, p. 1-11',
    citations: 16,
    scopus: 17,
  },
  {
    year: 2021,
    authors: 'BERGAMIN, M. F. K.; CARVALHO DOS SANTOS, I. G.; SCHEFFER, M. C.; CHALKIDIS, H. M.; LUCKWU DE SOUSA, R.; SILVA, K. E. R.; MOURA, V. M.; DOS-SANTOS, MARÍA CRISTINA',
    title: 'Individual variation in venom from the left and right glands of snakes of the species Bothrops atrox',
    venue: 'Scientia Amazonia',
    details: 'v. 10, p. CB1-CB12',
  },
  {
    year: 2021,
    authors: 'SOUZA, M. V. A.; LIMA JUNIOR, S. A. S.; PEREIRA, E. M. P.; LUCAS, A. C. S.; DOS-SANTOS, MARÍA CRISTINA',
    title: 'Projeto MEDensina: relato histórico de vinte anos de atuação',
    venue: 'Scientia Amazonia',
    details: 'v. 10, p. B15-B25',
    highlight: 1,
  },
  {
    year: 2021,
    authors: 'BATISTA, L. T.; SILVA, K. E. R.; DOS SANTOS, MARIA CRISTINA',
    title: 'Plantas Medicinais e Fitoterápicos no sistema de saúde brasileiro: uma revisão da literatura',
    venue: 'Scientia Amazonia',
    details: 'v. 10, p. CS69-CS83',
  },
  {
    year: 2021,
    authors: 'GOMES, V. T.; ALMEIDA, P. D. O.; FORTES-DIAS, C. L.; DOS-SANTOS, MARIA CRISTINA; CARVALHO DOS SANTOS, I. G.',
    title: 'Avaliação da atividade citotóxicas das frações CA e CB do veneno variedade branca de Crotalus durissus ruruima',
    venue: 'Scientia Amazonia',
    details: 'v. 10, p. B1-B13',
  },
  {
    year: 2020,
    authors: 'SOARES PESSOA, B. M.; BARROSO, C. T.; VILA, D. J. C.; BARBOSA, E. M. L.; SEFFAIR, I. A.; OLIVEIRA DE MELO, J. V.; BECIL, J. N.; RODRIGUES, N. M. V.; FREITAS, P. H. A. G.; BUSTAMANTE-ROCHA, R.; BENTES, T. M.; RODRIGUES, T. F.; DOS-SANTOS, MARIA CRISTINA; BOECHAT, A. L. R.',
    title: 'IMUNOTERAPIAS NO TRATAMENTO DA COVID-19',
    venue: 'Desafios: Revista Interdisciplinar da Universidade Federal do Tocantins',
    details: 'v. 7, p. 97-108',
  },
  {
    year: 2020,
    authors: 'GUIMARAES, N. C.; FREITAS-DE-SOUSA, L. A.; SOUZA, M. C. S.; ALMEIDA, P. D. O.; DOS-SANTOS, M. C.; NUNEZ, C. V.; OLIVEIRA, R. B.; MOURÃO, R. H. V.; MOURA, V. M.',
    title: 'Evaluation of the anti-snakebite, antimicrobial and antioxidant potential of Philodendron megalophyllum Schott (Araceae), traditionally used in accidents caused by snakes in the western region of Pará, Brazil',
    venue: 'Toxicon',
    details: 'v. 184, p. 99-108',
    citations: 7,
    scopus: 9,
  },
  {
    year: 2020,
    authors: 'LUCKWU DE SOUSA, R.; CARVALHO DOS SANTOS, I. G.; SILVA, K. E. R.; BARCELLOS, J. F. M.; COSTA, O. T. F.; DOS-SANTOS, MARIA CRISTINA',
    title: 'Infectious agents and parasites that affect tambaqui (Colossoma macropomum) and treatments used to control these pathogens: a systematic review',
    venue: 'Scientia Amazonia',
    details: 'v. 9, p. B1-B25',
  },
  {
    year: 2020,
    authors: 'LAMEIRAS, J. L. V.; MOURA, V. M.; CASTANHOLA-DIAS, L.; PESSOA JR., E. R.; MALMANN, CACILDA SATOMY YANO; COSTA, A. G.; NUNEZ, C. V.; COSTA, O. T. F.; DOS-SANTOS, M. C.',
    title: 'Neutralization of the edema-forming and myotoxic activities of the venom of Potamotrygon motoro Müller and Henle, 1841 (Chondrichthyes — Potamotrygoninae) by antivenoms and circulating immunoglobulins',
    venue: 'Toxicon',
    details: 'v. 186, p. 126-140',
    citations: 2,
    scopus: 2,
    highlight: 1,
  },
  {
    year: 2019,
    authors: 'DA COSTA, OSCAR TADEU FERREIRA; DIAS, LUCAS CASTANHOLA; MALMANN, CACILDA SATOMY YANO; DE LIMA FERREIRA, CÉSAR AUGUSTO; DO CARMO, IRACIMAR BATISTA; WISCHNESKI, ANDREW GEORG; DE SOUSA, RAFAEL LUCKWU; CAVERO, BRUNO ADAN SAGRATZKI; LAMEIRAS, JULIANA LUIZA VARJÃO; DOS-SANTOS, MARIA CRISTINA',
    title: 'The effects of stocking density on the hematology, plasma protein profile and immunoglobulin production of juvenile tambaqui (Colossoma macropomum) farmed in Brazil',
    venue: 'Aquaculture',
    details: 'v. 499, p. 260-268',
    citations: 46,
    scopus: 45,
    highlight: 1,
  },
  {
    year: 2019,
    authors: 'LAMEIRAS, J. L. V.; COSTA, O. T. F.; DOS-SANTOS, MARIA CRISTINA',
    title: 'Neotropical freshwater stingrays (Chondrichthyes — Potamotrygoninae): biology, general features and envenomation',
    venue: 'Toxin Reviews',
    details: 'v. 38, p. 1-16',
    citations: 3,
    scopus: 4,
  },
  {
    year: 2019,
    authors: 'KIELING, A. C.; SANTANA, G. P.; DOS-SANTOS, MARIA CRISTINA',
    title: 'COMPÓSITOS DE MADEIRA PLÁSTICA: CONSIDERAÇÕES GERAIS',
    venue: 'Scientia Amazonia',
    details: 'v. 8, p. B1-B14',
  },
  {
    year: 2019,
    authors: 'FERNANDES DA SILVA, B.; SOUZA-MARQUES, A. F.; SOUZA, E. M. O.; DOS-SANTOS, M. C.',
    title: 'Mastite Canina: Uma Revisão',
    venue: 'Scientia Amazonia',
    details: 'v. 8, p. MV1-MV7',
  },
  {
    year: 2019,
    authors: 'KIELING, A. C.; SANTANA, G. P.; DOS-SANTOS, MARIA CRISTINA; SILVA, C. S. S.; AMORIM, C. L. S.; PONTES, J. R.',
    title: 'POTENCIAL ECONÔMICO DE PLÁSTICOS RECICLÁVEIS NA CIDADE DE MANAUS (AM)',
    venue: 'Scientia Amazonia',
    details: 'v. 8, p. CAM1-CAM15',
  },
  {
    year: 2019,
    authors: 'KIELING, A. C.; SANTANA, G. P.; DOS-SANTOS, MARIA CRISTINA; JAQTINON, H. C. C.; MONTEIRO, C. C. P.',
    title: 'CADEIA DO TUCUMÃ COMERCIALIZADO EM MANAUS-AM',
    venue: 'Scientia Amazonia',
    details: 'v. 8, p. B1-B9',
  },
  {
    year: 2019,
    authors: 'SOUZA, M. C. S.; MOURA, V. M.; CARVALHO DOS SANTOS, I. G.; NUNEZ, C. V.; DOS SANTOS, MARIA CRISTINA',
    title: 'Avaliação do potencial antimicrobiano e antiofídico de Casearia javitensis (Salicaceae)',
    venue: 'Scientia Amazonia',
    details: 'v. 8, p. B8-B17',
  },
  {
    year: 2019,
    authors: 'MELO-SOUZA, D. C.; DOS-SANTOS, MARIA CRISTINA; CHAGAS, E. C.',
    title: 'Immune response of teleost fish to helminth parasite infection',
    venue: 'Revista Brasileira de Parasitologia Veterinária',
    details: 'p. 1-15',
    citations: 34,
    scopus: 35,
  },
  {
    year: 2019,
    authors: 'EUZÉBIO-RIBEIRO, S. L.; PEREIRA, H.; BOECHAT, A. L. R.; SATO, E.; CUNHA, M. C. F.; SOUZA PASSOS, L. F.; DOS-SANTOS, MARIA CRISTINA',
    title: 'Epidemiological, clinical and immune factors that influence the persistence of antiphospholipid antibodies in leprosy',
    venue: 'Advances in Rheumatology',
    details: 'v. 59, p. 1-7',
    citations: 6,
    scopus: 8,
  },
  {
    year: 2019,
    authors: 'DE CARVALHO, ANA EDUARDA ZULIM; GIANNOTTI, KARINA; JUNIOR, ELBIO LEIGUEZ; MATSUBARA, MÁRCIO; SANTOS, MARIA CRISTINA DOS; FORTES-DIAS, CONSUELO LATORRE; TEIXEIRA, CATARINA',
    title: 'Snake Venom and a Phospholipase A₂ Isolated from This Venom Elicit Macrophages to Form Lipid Droplets and Synthesize Inflammatory Lipid Mediators',
    venue: 'Journal of Immunology Research',
    details: 'v. 2019, p. 1-12',
    citations: 13,
    scopus: 13,
  },
  {
    year: 2019,
    authors: 'RICARDO, P. C.; SANTANA, L. K. L.; OLIVEIRA, S. K. M.; SERUDO, R. L.; LIMA-PASMAR, M.; DOS-SANTOS, MARIA CRISTINA',
    title: 'A new carbon-paste immunosensor for quantification of tumor necrosis factor-alpha (TNF-α) in human serum',
    venue: 'Scientia Amazonia',
    details: 'v. 8, p. B18-B30',
  },
  {
    year: 2018,
    authors: 'FONSECA, J. S.; SERUDO, R. L.; DOS-SANTOS, M. C.',
    title: 'MATRIZ ENERGÉTICA BRASILEIRA: TECNOLOGIAS COMPLEMENTARES',
    venue: 'Scientia Amazonia',
    details: 'v. 7, p. 74-88',
  },
  {
    year: 2018,
    authors: 'DE MOURA, VALÉRIA MOURÃO; DA COSTA GUIMARÃES, NORANATHAN; BATISTA, LUANA TRAVASSOS; FREITAS-DE-SOUSA, LUCIANA A.; DE SOUSA MARTINS, JOANDERSON; DE SOUZA, MARIA CAROLINA SCHEFFER; OLIVEIRA DE ALMEIDA, PATRÍCIA D.; MONTEIRO, WUELTON MARCELO; DE OLIVEIRA, RICARDO BEZERRA; DOS-SANTOS, MARIA CRISTINA; MOURÃO, ROSA HELENA VERAS',
    title: 'Assessment of the anti-snakebite properties of extracts of Aniba fragrans Ducke (Lauraceae) used in folk medicine as complementary treatment in cases of envenomation by Bothrops atrox',
    venue: 'Journal of Ethnopharmacology',
    details: 'v. 213, p. 350-358',
    citations: 18,
    scopus: 21,
  },
  {
    year: 2018,
    authors: 'DOS SANTOS, ILIA GILMARA CARVALHO; ALMEIDA, P. D. O.; DE SOUZA, MARIA CAROLINA SCHEFFER; SOUSA, L. B.; BARBOSA, A. R. C.; LAMEIRAS, J. L. V.; LIMA, E. S.; VASCONCELLOS, M. C.; NUNEZ, C. V.; BOECHAT, A. L. R.; FORTES-DIAS, C. L.; DOS-SANTOS, MARIA CRISTINA',
    title: 'Antitumor and antibacterial activity of white and yellow venoms of Crotalus durissus ruruima tested individually',
    venue: 'Scientia Amazonia',
    details: 'v. 7, p. b1-b14',
  },
  {
    year: 2018,
    authors: 'PINTO, P. T.; MENDONÇA, A. P.; DOS-SANTOS, M. C.',
    title: 'Aplicativo Móvel para Notificação de Acidentes por Arraias',
    venue: 'Revista de Informática Aplicada',
    details: 'v. 14, p. 1-16',
  },
  {
    year: 2017,
    authors: 'FIGUEIREDO, A. R.; WANDERLEY, B. G.; VILAS BOAS, T. S.; DOS-SANTOS, MARIA CRISTINA',
    title: 'Estudo da eficiência dos portais ScienceDirect, Scopus, Lilacs e Periódicos Capes, evidenciando seus aspectos positivos e negativos',
    venue: 'Scientia Amazonia',
    details: 'v. 6, p. 1-10',
  },
  {
    year: 2017,
    authors: 'SANTANA, L. K. L.; RICARDO, P. C.; SERUDO, R. L.; LIMA-PASMAR, M.; DOS-SANTOS, MARIA CRISTINA',
    title: 'Imunossensores eletroquímicos e suas aplicações',
    venue: 'Scientia Amazonia',
    details: 'v. 6, p. 31',
  },
  {
    year: 2017,
    authors: 'CARVALHO DOS SANTOS, I. G.; FORTES-DIAS, C. L.; DOS-SANTOS, MARIA CRISTINA',
    title: 'Aplicações farmacológicas dos venenos de serpentes brasileiras: enfoque para Crotalus durissus terrificus e Crotalus durissus ruruima',
    venue: 'Scientia Amazonia',
    details: 'v. 6, p. 42-53',
  },
  {
    year: 2017,
    authors: 'PEREIRA DA SILVA, T.; MOURA, V. M.; DE SOUZA, LUANA YAMILLE ANDRADE; LUCKWU-SOUSA, R.; MOURAO, R. H. V.; DOS-SANTOS, MARIA CRISTINA',
    title: 'Espécies vegetais utilizadas no bloqueio da atividade hemorrágica induzida pelos venenos de serpentes do gênero Bothrops sp.: uma revisão da literatura',
    venue: 'Scientia Amazonia',
    details: 'v. 6, p. 36-57',
  },
  {
    year: 2017,
    authors: 'LAMEIRAS, J. L. V.; MOURA, V. M.; CASTANHOLA-DIAS, L.; CARVALHO DOS SANTOS, I. G.; COSTA, O. T. F.; DOS-SANTOS, M. C.',
    title: 'Cross-reactivity between antivenoms and dorsal and stinger extracts of others stingrays (Chondrichthyes: Potamotrygonidae) from the Amazon basin',
    venue: 'Toxin Reviews',
    details: 'v. 36, p. 1-10',
    citations: 3,
    scopus: 4,
  },
  {
    year: 2017,
    authors: 'DE MOURA, VALÉRIA MOURÃO; DE SOUZA, LUANA YAMILLE ANDRADE; DA COSTA GUIMARÃES, NORANATHAN; DOS SANTOS, ILIA GILMARA CARVALHO; DE ALMEIDA, PATRÍCIA DANIELLE OLIVEIRA; DE OLIVEIRA, RICARDO BEZERRA; MOURÃO, ROSA HELENA VERAS; DOS-SANTOS, MARIA CRISTINA',
    title: 'The potential of aqueous extracts of Bellucia dichotoma Cogn. (Melastomataceae) to inhibit the biological activities of Bothrops atrox venom: A comparison of specimens collected in the states of Pará and Amazonas, Brazil',
    venue: 'Journal of Ethnopharmacology',
    details: 'v. 196, p. 168-177',
    citations: 12,
    scopus: 15,
    highlight: 1,
  },
  {
    year: 2016,
    authors: 'PEREIRA DA SILVA, T.; MOURA, V. M.; SCHEFFER, M. C.; SANTOS, V. N. C.; SILVA, K. A. M. M.; MENDES, M. G. G.; NUNEZ, C. V.; ALMEIDA, P. D. O.; LIMA, E. S.; MOURAO, R. H. V.; DOS-SANTOS, MARIA CRISTINA',
    title: 'Connarus favosus Planch.: an inhibitor of the hemorrhagic activity of Bothrops atrox venom and a potential antioxidant and antibacterial agent',
    venue: 'Journal of Ethnopharmacology',
    details: 'v. 183, p. 166-175',
    citations: 15,
    scopus: 16,
  },
  {
    year: 2016,
    authors: 'MOURA, V. M.; SILVA, W. C. R.; RAPOSO, J. D. A.; FREITAS-DE-SOUSA, L. A.; DOS-SANTOS, MARIA CRISTINA; OLIVEIRA, R. B.; MOURAO, R. H. V.',
    title: 'The inhibitory potential of the condensed-tannin-rich fraction of Plathymenia reticulata Benth. (Fabaceae) against Bothrops atrox envenomation',
    venue: 'Journal of Ethnopharmacology',
    details: 'v. 183, p. 136-142',
    citations: 28,
    scopus: 27,
  },
  {
    year: 2016,
    authors: 'MOREIRA, V.; TEIXEIRA, C.; D’IMPÉRIO LIMA, MARIA REGINA; DA SILVA, HENRIQUE BORGES; DOS-SANTOS, MARIA CRISTINA',
    title: 'The role of TLR2 in the acute inflammatory response induced by Bothrops atrox snake venom',
    venue: 'Toxicon (Oxford)',
    details: 'v. 118, p. 121-128',
    citations: 32,
    scopus: 29,
  },
  {
    year: 2016,
    authors: 'GUALBERTO, R. M.; MENDONÇA, A. P.; DOS-SANTOS, MARIA CRISTINA',
    title: 'Uma Contribuição para a Notificação de Acidentes com Arraias: Desenvolvimento de um Sistema Web para Gerir as Notificações',
    venue: 'Journal of Health Informatics',
    details: 'v. 8, p. 57-65',
  },
  {
    year: 2016,
    authors: 'SÁ FERNANDES; BEZERRA-LIMA, M.; DOS-SANTOS, MARIA CRISTINA; NUNES, F. D.; GALLOTTINI, M.',
    title: 'Salivary Immunoglobulins in Individuals with Common Variable Immunodeficiency',
    venue: 'Brazilian Dental Journal',
    details: 'v. 27, p. 641-645',
    scopus: 4,
  },
  {
    year: 2015,
    authors: 'MOURA, V. M.; SOUSA, L. A. F.; LIMA, A. E.; DOS-SANTOS, M. C.; RAPOSO, J. D. A.; OLIVEIRA, R. B.; SILVA, M. N.; ARRUDA, A. C.; MOURAO, R. H. V.',
    title: 'Plants used to treat snakebites in Santarém, western Pará, Brazil: An assessment of their effectiveness in inhibiting hemorrhagic activity induced by Bothrops jararaca venom',
    venue: 'Journal of Ethnopharmacology',
    details: 'v. 161, p. 224-232',
    citations: 46,
    scopus: 44,
  },
  {
    year: 2015,
    authors: 'MOURA, V. M.; MOURAO, R. H. V.; DOS-SANTOS, MARIA CRISTINA',
    title: 'Acidentes ofídicos na Região Norte do Brasil e o uso de espécies vegetais como tratamento alternativo e complementar à soroterapia',
    venue: 'Scientia Amazonia',
    details: 'v. 4, p. 73-84',
    scopus: 1,
  },
  {
    year: 2015,
    authors: 'FAN, H. W.; MONTEIRO, W. M.; MOURA DA SILVA, A. M.; TAMBOURGI, D. V.; SILVA, I. M.; SAMPAIO, V.; DOS-SANTOS, M. C.; SACHETT, J.; FERREIRA, LUIZ CARLOS DE LIMA; KALIL, J.; LACERDA, M.',
    title: 'Snakebites and Scorpion Stings in the Brazilian Amazon: Identifying Research Priorities for a Largely Neglected Problem',
    venue: 'PLoS Neglected Tropical Diseases (Online)',
    details: 'v. 9, p. e0003701',
    citations: 91,
    scopus: 95,
    highlight: 1,
  },
  {
    year: 2015,
    authors: 'VASCONCELLOS-DIAS, C. A. C.; GOES FILHO, J. D.; OLIVEIRA, R. R. C.; LUCKWU-SOUSA, R.; DUNCAN, W. L. P.; ONO, E.; MARIUBA, L. A. M.; LAMEIRAS, J. V.; DOS-SANTOS, M. C.',
    title: 'Caracterização parcial das imunoglobulinas de Plesiotrygon iwamae (Chondrichtyes — Potamotrygonidae) e de Colossoma macropomum (Osteichtyes — Characidae) isoladas com ácido caprílico',
    venue: 'Scientia Amazonia',
    details: 'v. 4, p. 1-9',
  },
  {
    year: 2015,
    authors: 'FEITOSA, E.; SACHETT, J.; SILVA, I. M.; DOS-SANTOS, MARIA CRISTINA; FERREIRA, L. C. L.; LACERDA, M.; MONTEIRO, W. M.',
    title: 'Older Age and Time to Medical Assistance Are Associated with Severity and Mortality of Snakebites in the Brazilian Amazon: A Case-Control Study',
    venue: 'PLoS One',
    details: 'v. 10, p. e0132237',
    citations: 99,
    scopus: 102,
    highlight: 1,
  },
  {
    year: 2014,
    authors: 'LAMEIRAS, J. L. V.; COSTA, O. T. F.; MORONI, F. T.; ARAÚJO, J. R.; CARANHAS, S. M. E.; MARQUES, C. M. A.; DOS-SANTOS, M. C.; DUNCAN, W. L. P.',
    title: 'Systemic rhabdomyolysis induced by venom of freshwater stingrays Plesiotrygon iwamae and Potamotrygon motoro (Chondrichthyes — Potamotrygonidae) from the Amazon Basin',
    venue: 'Toxicon (Oxford)',
    details: 'v. 77, p. 105-113',
    citations: 13,
    scopus: 14,
  },
  {
    year: 2014,
    authors: 'DOS-SANTOS, MARIA CRISTINA',
    title: 'Crotoxina e Crotoxina-símile isoladas de venenos de subespécies de Crotalus durissus e suas múltiplas atividades biológicas',
    venue: 'Scientia Amazonia',
    details: 'v. 3, p. 102-115',
  },
  {
    year: 2014,
    authors: 'EUZÉBIO-RIBEIRO, S. L.; PEREIRA, H.; SILVA, N.; SATO, E.; SOUZA PASSOS, L. F.; DOS-SANTOS, MARIA CRISTINA',
    title: 'Long-term persistence of anti-β2 glycoprotein I in treated leprosy patients',
    venue: 'Lupus (Basingstoke)',
    details: 'v. 23, p. 1249-1251',
    citations: 6,
    scopus: 5,
  },
  {
    year: 2014,
    authors: 'MOURA, V. M.; BEZERRA, A. N. S.; MOURAO, R. H. V.; LAMEIRAS, J. L. V.; RAPOSO, J. D. A.; LUCKWU-SOUSA, R.; BOECHAT, A. L.; OLIVEIRA, R. B.; CHALKIDIS, H. M.; DOS-SANTOS, MARIA CRISTINA',
    title: 'A comparison of the ability of Bellucia dichotoma Cogn. (Melastomataceae) extract to inhibit the local effects of Bothrops atrox venom when pre-incubated and when used according to traditional methods',
    venue: 'Toxicon (Oxford)',
    details: 'v. 85, p. 59-68',
    citations: 19,
    scopus: 22,
  },
  {
    year: 2014,
    authors: 'NAIFF, PRISCILLA F.; FERRAZ, RAQUEL; CUNHA, CLARISSA F.; ORLANDI, PATRÍCIA P.; BOECHAT, ANTÔNIO LUIZ; BERTHO, ÁLVARO L.; DOS-SANTOS, MARIA CRISTINA',
    title: 'Immunophenotyping in Saliva as an Alternative Approach for Evaluation of Immunopathogenesis in Chronic Periodontitis',
    venue: 'Journal of Periodontology (1970)',
    details: 'v. 85, p. e111-e120',
    citations: 8,
    scopus: 13,
  },
  {
    year: 2014,
    authors: 'EUZÉBIO-RIBEIRO, S. L.; SOUZA PASSOS, L. F.; DOS-SANTOS, M. C.',
    title: 'Anticorpos naturais e autoanticorpos na Hanseníase',
    venue: 'Scientia Amazonia',
    details: 'v. 3, p. 1-19',
  },
  {
    year: 2013,
    authors: 'BOECHAT, A. L.; OGUSKU, MAURICIO MORISHI; BOECHAT, N. O.; ALENCAR, M. R.; ABENSUR, T. C.; CARDOSO-NETO, J.; AMORIN, L.; M. OLIVEIRA, L.; SADAHIRO, A.; DOS-SANTOS, M. C.',
    title: 'The influence of a TNF gene polymorphism on the severity of rheumatoid arthritis in the Brazilian Amazon',
    venue: 'Cytokine',
    details: 'v. 61, p. 406-412',
    citations: 12,
    scopus: 12,
  },
  {
    year: 2013,
    authors: 'BOECHAT, ANTONIO LUIZ; OGUSKU, MAURICIO MORISHI; SADAHIRO, AYA; DOS SANTOS, MARIA CRISTINA',
    title: 'Association between the PTPN22 1858C/T gene polymorphism and tuberculosis resistance',
    venue: 'Infection, Genetics and Evolution (Print)',
    details: 'v. 16, p. 310-313',
    citations: 23,
    scopus: 24,
  },
  {
    year: 2013,
    authors: 'LAMEIRAS, J. L. V.; COSTA, O. T. F.; DOS-SANTOS, M. C.; DUNCAN, W. L. P.',
    title: 'Arraias de água doce (Chondrichthyes — Potamotrygonidae): Biologia, Veneno e Acidentes',
    venue: 'Scientia Amazonia',
    details: 'v. 2, p. 11-27',
  },
  {
    year: 2013,
    authors: 'D’IMPERIO LIMA, M. R.; MOREIRA, VANESSA; TEIXEIRA, CATARINA; BORGES DA SILVA, HENRIQUE; DOS-SANTOS, M. C.',
    title: 'The crucial role of the MyD88 adaptor protein in the inflammatory response induced by Bothrops atrox venom',
    venue: 'Toxicon (Oxford)',
    details: 'v. 41, p. 71-78',
    citations: 24,
    scopus: 20,
  },
  {
    year: 2012,
    authors: 'MOREIRA, VANESSA; DOS-SANTOS, MARIA CRISTINA; NASCIMENTO, NEIDE GALVÃO; DA SILVA, HENRIQUE BORGES; FERNANDES, CRISTINA MARIA; D’IMPÉRIO LIMA, MARIA REGINA; TEIXEIRA, CATARINA',
    title: 'Local inflammatory events induced by Bothrops atrox snake venom and the release of distinct classes of inflammatory mediators',
    venue: 'Toxicon (Oxford)',
    details: 'v. 60, p. 12-20',
    citations: 67,
    scopus: 69,
    highlight: 1,
  },
  {
    year: 2012,
    authors: 'GARCIA, J. B. S.; CARDOSO, M. G. M.; DOS-SANTOS, MARIA CRISTINA',
    title: 'Opioides e o sistema imunológico: relevância clínica',
    venue: 'Revista Brasileira de Anestesiologia',
    details: 'v. 62, p. 713-718',
  },
  {
    year: 2012,
    authors: 'NAIFF, P. F.; ORLANDI, P. P.; DOS-SANTOS, MARIA CRISTINA',
    title: 'Imunologia da Periodontite Crônica: uma revisão de literatura',
    venue: 'Scientia Amazonia',
    details: 'v. 1, p. 28-36',
  },
  {
    year: 2011,
    authors: 'DOS-SANTOS, MARÍA CRISTINA; ARROYO, CYNTHIA; SOLANO, SERGIO; HERRERA, MARÍA; VILLALTA, MAUREN; SEGURA, ÁLVARO; ESTRADA, RICARDO; GUTIÉRREZ, JOSÉ MARÍA; LEÓN, GUILLERMO',
    title: 'Comparison of the effect of Crotalus simus and Crotalus durissus ruruima venoms on the equine antibody response towards Bothrops asper venom: implications for the production of polyspecific snake antivenoms',
    venue: 'Toxicon (Oxford)',
    details: 'v. 57, p. 237-243',
    citations: 9,
    scopus: 9,
  },
  {
    year: 2011,
    authors: 'MAGALHÃES, A. O.; VOLKMER-RIBEIRO, C.; FUJIMOTO, L. B. M.; BARBOSA, M. F.; CARDOSO, J. L.; BARCELLOS, J. F. M.; SILVA, C. C.; CAMPOS, R. R.; CUNHA, M. C. F.; FREITAS-LEMOS, A. P.; DOS-SANTOS, M. C.',
    title: 'Induction of cell migration and activation in mice by the freshwater sponge Drulia uruguayensis Bonetto & Ezcurra de Drago, 1968 (Porifera: Metaniidae)',
    venue: 'The Journal of Venomous Animals and Toxins Including Tropical Diseases (Online)',
    details: 'v. 17, p. 66-73',
    citations: 3,
    scopus: 4,
  },
  {
    year: 2011,
    authors: 'MAGALHÃES, A. L.; SANTOS, G. B.; VERDAM, MARIA CHRISTINA DOS SANTOS; FRAPORTI, L. S.; MALHEIRO, A.; LIMA, E. S.; DOS-SANTOS, MARIA CRISTINA',
    title: 'Inhibition of the inflammatory and coagulant action of Bothrops atrox venom by the plant species Marsypianthes chamaedrys',
    venue: 'Journal of Ethnopharmacology',
    details: 'v. 134, p. 82-88',
    citations: 35,
    scopus: 38,
  },
  {
    year: 2011,
    authors: 'ALCÂNTARA, ANTÔNIO FLAVIO DE CARVALHO; VELOSO, D. P.; FERNANDES, A. J.; DOS-SANTOS, MARIA CRISTINA',
    title: 'Theoretical Investigation of the Structural Properties of Two Crotamines',
    venue: 'The Open Natural Products Journal',
    details: 'v. 4, p. 16-20',
    scopus: 1,
  },
  {
    year: 2011,
    authors: 'KATSURAYAMA, MARILISE; GOMES, N. M.; BECKER, M. A. D’A.; DOS-SANTOS, MARIA CRISTINA; MAKIMOTO, F. H.; SANTANA, L. L. O.',
    title: 'Avaliação dos níveis de estresse psicológico em Médicos Residentes e não-Residentes de Hospitais Universitários',
    venue: 'Psicologia Hospitalar',
    details: 'v. 9, p. 75-96',
  },
  {
    year: 2010,
    authors: 'CALVETE, JUAN J.; SANZ, LIBIA; CID, PEDRO; DE LA TORRE, PILAR; FLORES-DÍAZ, MARIETTA; DOS SANTOS, M. CRISTINA; BORGES, ADOLFO; BREMO, ADOLFO; ANGULO, YAMILETH; LOMONTE, BRUNO; ALAPE-GIRÓN, ALBERTO; GUTIÉRREZ, JOSÉ MARÍA',
    title: 'Snake Venomics of the Central American Rattlesnake Crotalus simus and the South American Crotalus durissus Complex Points to Neurotoxicity as an Adaptive Paedomorphic Trend along Crotalus Dispersal in South America',
    venue: 'Journal of Proteome Research',
    details: 'v. 9, p. 528-544',
    citations: 170,
    scopus: 218,
    highlight: 1,
  },
  {
    year: 2010,
    authors: 'ALBUQUERQUE, SÉRGIO ROBERTO LOPES; OLIVEIRA CAVALCANTE, FRANCIMARY; SANGUINO, EDALTON CESAR; TEZZA, LUCIANNA; CHACON, FERNANDA; CASTILHO, LILIAN; DOS-SANTOS, MARIA CRISTINA',
    title: 'FY polymorphisms and vivax malaria in inhabitants of Amazonas State, Brazil',
    venue: 'Parasitology Research',
    details: 'v. 106, p. 1049-1053',
    citations: 25,
    scopus: 24,
  },
  {
    year: 2010,
    authors: 'MATOS-GOMES, NATHÁLIA; SANTANA, LINDA LUCIANA OLIVEIRA; DOS-SANTOS, M. C.; KATSURAYAMA, MARILISE; PAREDES-GARCIA, EDIJANE; BECKER, MARIA ALICE D’ÁVILA; MAKIMOTO, FABIANO HIROMICHI',
    title: 'Psychological Stress and Its Influence on Salivary Flow Rate, Total Protein Concentration and IgA, IgG and IgM Titers',
    venue: 'Neuroimmunomodulation',
    details: 'v. 17, p. 396-404',
    citations: 47,
    scopus: 50,
    highlight: 1,
  },
  {
    year: 2009,
    authors: 'KATSURAYAMA, M.; D’ÁVILA-BECKER, M. A.; GOMES, N. M.; DOS-SANTOS, M. C.; MAKIMOTO, F.; SANTANA, L.',
    title: 'Fatores de risco e proteção em estudantes de Medicina da Universidade Federal do Amazonas',
    venue: 'Psicología para América Latina',
    details: 'v. 16, p. 1-18',
  },
  {
    year: 2009,
    authors: 'DOS-SANTOS, M. C.; MATOS-GOMES, NATHÁLIA; MAKIMOTO, FABIANO HIROMICHI; KATSURAYAMA, MARILISE; SANTANA, LINDA LUCIANA OLIVEIRA; ALICE D’ÁVILA BECKER, MARIA; PAREDES-GARCIA, EDIJANE; BERTHO, ÁLVARO L.',
    title: 'Cell phenotyping in saliva of individuals under psychological stress',
    venue: 'Cellular Immunology (Print)',
    details: 'v. 260, p. 39-43',
    citations: 9,
    scopus: 10,
  },
  {
    year: 2009,
    authors: 'NEGREIROS, RÓBSON MIGUEL DE ARAÚJO; MAKIMOTO, FABIANO HIROMICHI; SANTANA, LINDA LUCIANA OLIVEIRA; FERREIRA, LUÍS CARLOS DE LIMA; NAKAJIMA, GERSON SUGUIYAMA; SANTOS, MARIA CRISTINA DOS',
    title: 'Experimental splenectomies and malaria in mice',
    venue: 'Acta Cirurgica Brasileira (Impresso)',
    details: 'v. 24, p. 437-441',
    citations: 5,
    scopus: 5,
  },
  {
    year: 2009,
    authors: 'ALBUQUERQUE, SÉRGIO ROBERTO L.; DOS-SANTOS, MARIA CRISTINA',
    title: 'Associações entre os fenótipos ABO, RhD, mutações da proteína Duffy e a malária vivax em habitantes do estado do Amazonas, Brasil',
    venue: 'Revista Brasileira de Hematologia e Hemoterapia (Impresso)',
    details: 'v. 31, p. 299-300',
    citations: 5,
    scopus: 1,
  },
  {
    year: 2008,
    authors: 'COSTA, HABDEL NASSER ROCHA DA; SANTOS, MARIA CRISTINA DOS; ALCÂNTARA, ANTÔNIO FLAVIO DE CARVALHO; SILVA, MARILDA CONCEIÇÃO; FRANÇA, ROBERTA CABRAL; PILÓ-VELOSO, DORILA',
    title: 'Constituintes químicos e atividade antiedematogênica de Peltodon radicans (Lamiaceae)',
    venue: 'Química Nova (Impresso)',
    details: 'v. 31',
    citations: 4,
    scopus: 21,
  },
  {
    year: 2008,
    authors: 'MACHADO, A. L.; SANTANA, G. P.; DOS-SANTOS, M. C.',
    title: 'Waste Solid Management from Balbina Village, Presidente Figueiredo, Amazonas State — Brazil',
    venue: 'Caminhos de Geografia',
    details: 'v. 9, p. 19-25',
  },
  {
    year: 2007,
    authors: 'PASSOS, LUIZ FERNANDO; DOS-SANTOS, M. C.',
    title: 'Novos Paradigmas para a Medicina Genômica',
    venue: 'Jornal da LIRNNE',
    details: 'v. 3, p. 51-59',
  },
  {
    year: 2007,
    authors: 'PASSOS, LUIZ FERNANDO; DOS-SANTOS, M. C.',
    title: 'Apresentando Auto-antígenos: HLA e Artrite Reumatóide',
    venue: 'Jornal da LIRNNE',
    details: 'v. 3, p. 104-110',
  },
  {
    year: 2006,
    authors: 'SANTOS, ROSE MARY CORRÊA; OGUSKU, MAURICIO MORISHI; MIRANDA, JOSÉ DE MORAES; DOS-SANTOS, MARIA CRISTINA; SALEM, JULIA IGNEZ',
    title: 'Avaliação da reação em cadeia da polimerase no diagnóstico da tuberculose pulmonar em pacientes indígenas e não indígenas',
    venue: 'Jornal Brasileiro de Pneumologia (Impresso)',
    details: 'v. 32, n. 3, p. 234-240',
    citations: 6,
    scopus: 10,
  },
  {
    year: 2006,
    authors: 'ONO, LIA MIZOBE; ARAUJO, J. L. P.; DOS-SANTOS, M. C.',
    title: 'Componentes das imunidades inata e adaptativa presentes na saliva humana',
    venue: 'Revista de Odontologia da UNESP (Online)',
    details: 'v. 35, p. 253-261',
    scopus: 3,
  },
  {
    year: 2005,
    authors: 'DOS SANTOS, M.; ASSIS, E.; MOREIRA, T.; PINHEIRO, J.; FORTES-DIAS, C.; DOS-SANTOS, M. C.',
    title: 'Individual venom variability in Crotalus durissus ruruima snakes, a subspecies of Crotalus durissus from the Amazonian region',
    venue: 'Toxicon',
    details: 'v. 46, p. 958-961',
    citations: 26,
    scopus: 23,
  },
  {
    year: 2003,
    authors: 'FURTADO, M. F. D.; DOS-SANTOS, M. C.; KAMIGUTI, A. S.',
    title: 'Age-related biological activity of South American rattlesnake (Crotalus durissus terrificus) venom',
    venue: 'Journal of Venomous Animals and Toxins Including Tropical Diseases (Online)',
    details: 'v. 9, n. 2, p. 180-185',
    citations: 15,
    scopus: 8,
  },
  {
    year: 2001,
    authors: 'BOECHAT, ANTÔNIO LUIZ R.; PAIVA, CRISTIANO S.; FRANÇA, FRANCISCO OSCAR; DOS-SANTOS, MARIA CRISTINA',
    title: 'Heparin-antivenom association: differential neutralization effectiveness in Bothrops atrox and Bothrops erythromelas envenoming',
    venue: 'Revista do Instituto de Medicina Tropical de São Paulo (Impresso)',
    details: 'v. 43, n. 1, p. 7-14',
    citations: 6,
    scopus: 9,
  },
  {
    year: 1999,
    authors: 'BORGES, C. C.; SADAHIRO, M.; DOS-SANTOS, M. C.',
    title: 'Aspectos epidemiológicos e clínicos dos acidentes ofídicos ocorridos nos municípios do Estado do Amazonas',
    venue: 'Revista da Sociedade Brasileira de Medicina Tropical (Impresso)',
    details: 'v. 32, n. 2, p. 637-646',
    citations: 92,
    scopus: 71,
    highlight: 1,
  },
  {
    year: 1996,
    authors: 'BORGES, C. C.; CAVALCANTI NETO, A. J.; BOECHAT, A. L. R.; FRANCISCON, C. H.; ARRUDA, L. F. M. R.; DOS-SANTOS, M. C.',
    title: 'Eficácia da espécie vegetal Peltodon radicans Pohl (Labiatae = Lamiaceae) na neutralização da atividade edematogênica e a ineficácia do extrato vegetal Específico Pessoa na neutralização das principais atividades do veneno de Bothrops atrox',
    venue: 'Revista da Universidade do Amazonas: Série Ciências Biológicas',
    details: 'v. 1, n. 1, p. 97-113',
  },
  {
    year: 1996,
    authors: 'ANDRADE, D.; ABE, A.; DOS-SANTOS, M. C.',
    title: 'Is the venom related to diet and tail color during Bothrops moojeni ontogeny?',
    venue: 'Journal of Herpetology',
    details: 'v. 30, n. 2, p. 285-288',
    citations: 22,
    scopus: 26,
  },
  {
    year: 1994,
    authors: 'BARROS, A.; FERNANDES, D.; FERREIRA, L.; DOS-SANTOS, M. C.',
    title: 'Local effects induced by venoms from five species of genus Micrurus sp. (coral snakes)',
    venue: 'Toxicon',
    details: 'v. 32, p. 445-452',
    citations: 43,
    scopus: 45,
  },
  {
    year: 1994,
    authors: 'NISHIKAWA, A.; CARICATI, C.; LIMA, M.; DOS-SANTOS, M. C.; KIPNIS, T.; EICKSTEDT, V.; KNYSAK, I.; DA SILVA, M.',
    title: 'Antigenic cross-reactivity among the venoms from several species of Brazilian scorpions',
    venue: 'Toxicon',
    details: 'v. 32, p. 989-998',
    citations: 61,
    scopus: 61,
  },
  {
    year: 1994,
    authors: 'DOS-SANTOS, M. C.',
    title: 'Caracterização das atividades biológicas dos venenos das serpentes brasileiras',
    venue: 'Herpetologia no Brasil',
    details: 'v. 1, p. 102-106',
  },
  {
    year: 1994,
    authors: 'MORAIS, J.; DE FREITAS, M.; YAMAGUCHI, I.; DOS-SANTOS, M. C.; DA SILVA, W.',
    title: 'Snake antivenoms from hyperimmunized horses: Comparison of the antivenom activity and biological properties of their whole IgG and F(ab′)₂ fragments',
    venue: 'Toxicon',
    details: 'v. 32, p. 725-734',
    citations: 57,
    scopus: 61,
  },
  {
    year: 1994,
    authors: 'TAMBOURGI, D. V.; DOS-SANTOS, M. C.; FURTADO, M. F. D.; FREITAS, M. C. W.; DIAS-DA-SILVA, W.; KIPNIS, T. L.',
    title: 'Pro-inflammatory activities in Elapid snake venoms',
    venue: 'British Journal of Pharmacology',
    details: 'v. 112, p. 723-727',
    citations: 50,
    scopus: 50,
  },
  {
    year: 1994,
    authors: 'BARD, RAMZA; LIMA, JOSÉ CARLOS R. DE; SA NETO, RAYMUNDO PEREIRA DE; OLIVEIRA, SILAS GUEDES DE; SANTOS, MARIA CRISTINA DOS',
    title: 'Ineficácia do antiveneno botrópico na neutralização da atividade coagulante do veneno de Lachesis muta muta: relato de caso e comprovação experimental',
    venue: 'Revista do Instituto de Medicina Tropical de São Paulo (Impresso)',
    details: 'v. 36, p. 77-81',
    citations: 6,
    scopus: 23,
  },
  {
    year: 1993,
    authors: 'DOS-SANTOS, M. C.',
    title: 'Caracterización de las actividades biologicas de los venenos “amarillo” y “blanco” de Crotalus durissus ruruima comparados con el veneno de Crotalus durissus terrificus. Poder neutralizante de los antivenenos frente a los venenos de Crotalus durissus ruruima',
    venue: 'Toxicon',
    details: 'v. 31, p. 1459-1469',
    citations: 32,
    scopus: 31,
    highlight: 1,
  },
  {
    year: 1992,
    authors: 'DOS-SANTOS, MARIA CRISTINA; GONÇALVES, LUÍS ROBERTO DE CAMARGO; FORTES-DIAS, CONSUELO L.; CURY, YARA; GUTIÉRREZ, JOSÉ MARIA; FURTADO, MARIA DE FÁTIMA D.',
    title: 'A eficácia do antiveneno botrópico-crotálico na neutralização das principais atividades do veneno de Bothrops jararacussu',
    venue: 'Revista do Instituto de Medicina Tropical de São Paulo (Impresso)',
    details: 'v. 34, p. 77-83',
    citations: 26,
    scopus: 28,
  },
  {
    year: 1992,
    authors: 'TAMBOURGI, D. V.; CAMPOS, A. C. M. R.; FREITAS, M. C. W.; MAGNOLI, F. C.; DIAS-DA-SILVA, W.; EICKSTEDT, V. R. D.; DOS-SANTOS, M. C.; FURTADO, M. F. D.; KIPNIS, T. L.',
    title: 'Manipulation of the complement system by animal venoms',
    venue: 'Memórias do Instituto Butantan',
    details: 'v. 54, n. 2, p. 9-10',
    scopus: 1,
  },
  {
    year: 1991,
    authors: 'D’IMPÉRIO LIMA, M.; DOS-SANTOS, M. C.',
    title: 'Susceptibility of different strains of mice to South American rattlesnake (Crotalus durissus terrificus) venom: Correlation between lethal effect and creatine kinase release',
    venue: 'Toxicon',
    details: 'v. 29, p. 783-786',
    citations: 9,
    scopus: 15,
  },
  {
    year: 1991,
    authors: 'GUTIERREZ, J.; DOS-SANTOS, M. C.',
    title: 'Biochemical and pharmacological similarities between the venoms of newborn Crotalus durissus durissus and adult Crotalus durissus terrificus rattlesnakes',
    venue: 'Toxicon',
    details: 'v. 29, p. 1273-1277',
    citations: 51,
    scopus: 55,
  },
  {
    year: 1990,
    authors: 'MOURA DA SILVA, A.; DOS-SANTOS, M. C.',
    title: 'Antigenic cross-reactivity of venoms obtained from snakes of genus Bothrops',
    venue: 'Toxicon',
    details: 'v. 28, p. 181-188',
    citations: 18,
    scopus: 27,
  },
  {
    year: 1989,
    authors: 'DOS-SANTOS, M. C.; YAMAGUCHI, I. K.; CARICATTI, C. P.; HIGASHI, H. G.; DIAS-DA-SILVA, W.',
    title: 'Immunization of equines with phospholipase A₂ protects against the lethal effects of Crotalus durissus terrificus venom',
    venue: 'Brazilian Journal of Medical and Biological Research (Impresso)',
    details: 'v. 22, p. 509-512',
    citations: 8,
    scopus: 9,
  },
  {
    year: 1989,
    authors: 'DOS-SANTOS, M. C.; D’IMPÉRIO LIMA, M.; FURTADO, G.; COLLETTO, G.; KIPNIS, T.; DIAS-DA-SILVA, W.',
    title: 'Purification of F(ab′)₂ anti-snake venom by caprylic acid: A fast method for obtaining IgG fragments with high neutralization activity, purity and yield',
    venue: 'Toxicon',
    details: 'v. 27, p. 297-303',
    citations: 71,
    scopus: 74,
    highlight: 1,
  },
  {
    year: 1988,
    authors: 'DOS-SANTOS, M. C.; DINIZ, C.; WHITAKER-PACHECO, M.; DIAS-DA-SILVA, W.',
    title: 'Phospholipase A₂ injection in mice induces immunity against the lethal effects of Crotalus durissus terrificus venom',
    venue: 'Toxicon (Oxford)',
    details: 'v. 26, p. 207-213',
    citations: 22,
    scopus: 21,
  },
  {
    year: 1979,
    authors: 'HOGE, A. R.; RUSSO, C. R.; DOS-SANTOS, M. C.; FURTADO, M. F. D.',
    title: 'Snakes collected by Projeto Rondon XXII to Piauí, Brazil',
    venue: 'Memórias do Instituto Butantan',
    details: 'v. 42/43, p. 87-94',
    scopus: 2,
  },
];

/* ------------------------------------ livros publicados / organizados (3) */

const LIVROS = [
  {
    year: 2021,
    authors: 'UREÑA, N. M.; FERNANDES, G. V. L.; PORTELA, F. L. D.; SOUZA, M. C. S.; SARTIM, A. G.; BOECHAT, A. L. R.; DOS-SANTOS, MARIA CRISTINA',
    title: 'Integração dos Sistemas: Nervoso, Endócrino, Imune e da Microbiota intestinal, na manutenção da saúde — Uma visão geral da Psiconeuroimunologia',
    venue: 'Manaus: Amazon',
    details: '1. ed., 78 p.',
    kind: 'livro',
    highlight: 1,
  },
  {
    year: 2002,
    authors: 'DOS-SANTOS, M. C.; TOPAN, C. S. O.; LIMA, E. K. R.',
    title: 'Lixo: Curiosidades e Conceitos',
    venue: 'Manaus: Editora da Universidade Federal do Amazonas',
    details: '150 p.',
    kind: 'livro',
  },
  {
    year: 1996,
    authors: 'DOS-SANTOS, M. C.; MARTINS, M.; BOECHAT, A. L.; SA-NETO, R. P.; OLIVEIRA, A.',
    title: 'Serpentes de Interesse Médico da Amazônia',
    venue: 'Manaus: ABEU — Associação Brasileira das Editoras Universitárias',
    details: '64 p.',
    kind: 'livro',
    highlight: 1,
  },
];

/* ------------------------------------------ capítulos de livros (7) ---- */

const CAPITULOS = [
  {
    year: 2022,
    authors: 'CASTANHO, M. V. A.; FREITAS, R. Q.; SOUZA, M. V. A.; PEREIRA, E. M. P.; MENDOZA, C. V. N.; MAIA, J. G.; SILVA, I. P. DA; EVANGELISTA, M. E. L. R.; ALMEIDA, R. A. L.; DOS-SANTOS, MARIA CRISTINA',
    title: 'A dimensão da extensão universitária frente à pandemia de COVID-19: um relato de experiência',
    venue: 'In: Internacional Saúde Única (Interface Mundial). 4. ed. Recife: Even3 Publicações',
    details: 'p. 437-443',
    kind: 'capitulo',
  },
  {
    year: 2022,
    authors: 'CASTANHO, M. V. A.; ALAGIA, R. B. N.; MAKLOUF, A. P. N. R.; SOUSA, D. C. F.; FARIAS, M. R. DE; LUCENA, A. P.; TOMAZ FILHO, S. C.; SILVA, T. F. DA; FREITAS, R. Q.; DOS-SANTOS, MARIA CRISTINA',
    title: 'Importância do Outubro Rosa em Manaus e o Projeto MEDensina: um relato de experiência',
    venue: 'In: Internacional Saúde Única (Interface Mundial). 4. ed. Recife: Even3 Publicações',
    details: 'v. 1, p. 431-436',
    kind: 'capitulo',
  },
  {
    year: 2021,
    authors: 'MELO-SOUZA, D. C.; LUCKWU DE SOUSA, R.; CHAGAS, E. C.; DOS-SANTOS, MARIA CRISTINA',
    title: 'Imunologia dos peixes Amazônicos: o quanto conhecemos?',
    venue: 'In: Aquicultura na Amazônia: Estudos Técnico-Científicos e Difusão de Tecnologia. 1. ed. Ponta Grossa: Atena',
    details: 'v. 1, p. 296-312',
    kind: 'capitulo',
  },
  {
    year: 2009,
    authors: 'DOS-SANTOS, M. C.',
    title: 'Serpentes Peçonhentas e Ofidismo no Amazonas',
    venue: 'In: Animais Peçonhentos no Brasil. 2. ed. São Paulo: Sarvier',
    details: 'Organizadores: João Luiz Costa Cardoso, Francisco Oscar de Siqueira França, Fan Hui Wen, Ceila Maria Sant’Ana Málaque & Vidal Haddad Jr.',
    kind: 'capitulo',
    highlight: 1,
  },
  {
    year: 2009,
    authors: 'MACHADO, A. L.; DOS SANTOS, M. CRISTINA; SANTANA, G. P.',
    title: 'Gerenciamento integrado dos resíduos sólidos da vila de Balbina, no município de Presidente Figueiredo, Amazonas',
    venue: 'In: Pesquisa interdisciplinar em ciências do Meio Ambiente. Manaus: EDUA',
    details: 'v. 1, p. 305-320',
    kind: 'capitulo',
  },
  {
    year: 2003,
    authors: 'DOS-SANTOS, M. C.',
    title: 'Serpentes peçonhentas e ofidismo no Amazonas',
    venue: 'In: Animais peçonhentos no Brasil. Biologia, Clínica e Terapêutica dos Acidentes. 1. ed. São Paulo: Sarvier Editora e FAPESP',
    details: 'p. 115-125',
    kind: 'capitulo',
  },
  {
    year: 1997,
    authors: 'DOS-SANTOS, M. C.; MULLE, L. D.',
    title: 'Lachesis',
    venue: 'In: Acidentes com Animais Peçonhentos — Consulta Rápida. Porto Alegre: Hospital de Clínicas de Porto Alegre',
    details: 'p. 100-103',
    kind: 'capitulo',
  },
];

module.exports = { ARTIGOS, LIVROS, CAPITULOS };
